python run_aug.py \
    --output_dir=./saved_models \
    --tokenizer_name=microsoft/codebert-base \
    --model_name_or_path=microsoft/codebert-base \
    --do_train \
    --train_data_file=/home/talkad/Desktop/pragformer_projects/a_code/data_creator/json_c_cpp/train.jsonl \
    --eval_data_file=/home/talkad/Desktop/pragformer_projects/a_code/data_creator/json_c_cpp/valid.jsonl \
    --test_data_file=./home/talkad/Desktop/pragformer_projects/a_code/data_creator/json_c_cpp/test.jsonl \
    --num_train_epochs 8 \
    --block_size 256 \
    --train_batch_size 8 \
    --eval_batch_size 16 \
    --learning_rate 2e-5 \
    --max_grad_norm 1.0 \
    --seed 123456  2>&1 | tee train_c_cpp_replaced.log