#ifndef _FAKE_TYPEDEFS_H
#define _FAKE_TYPEDEFS_H

typedef int graph;
typedef int ImageFileHeader;
typedef int CHUNKS_DISTR_INTERF;
typedef int relu_layer_t;
typedef int UBspline_2d_s;
typedef int multi_UBspline_1d_s;
typedef int NUgrid;
typedef int QuESTEnv;
typedef int JDIMENSION;
typedef int join_func_t;
typedef int Time_Int_Params;
typedef int MinMAX;
typedef int q15_t;
typedef int Type;
typedef int CONFIG;
typedef int BCtype_z;
typedef int hclib_future_t;
typedef int IT_POINT_SET;
typedef int qreal;
typedef int dump_flags_t;
typedef int Individuo;
typedef int ta_record;
typedef int double_dense_matrix;
typedef int accessor_write_int;
typedef int MutantData;
typedef int csr_matrix;
typedef int stringList;
typedef int node_p;
typedef int Queue_v;
typedef int JSAMPROW;
typedef int sop_t;
typedef int Counts;
typedef int Intersection;
typedef int cufftResult;
typedef int cufftHandle;
typedef int Hit_Record;
typedef int VlKDTree;
typedef int FilterColor;
typedef int scatter_constant;
typedef int Secular;
typedef int VlGMMInitialization;
typedef int OLink;
typedef int Result;
typedef int Cluster;
typedef int Vec;
typedef int Tensor;
typedef int hash_set;
typedef int DOT_STRUCT;
typedef int student_record;
typedef int ipa_fn_summary;
typedef int function_summary;
typedef int ipa_call_summary;
typedef int FitnessFunc;
typedef int H5O_info_t;
typedef int update_t;
typedef int COO_ENTRY_INT;
typedef int call_summary;
// typedef int omp_allocator_handle_t;
typedef int bfs_result;
typedef int vect_t;
typedef int hwloc_obj_t;
typedef int volume_t;
typedef int cdata_ptr_res_t;
typedef int SOCKET;
typedef int SUNContext;
typedef int epair_t;
typedef int slist_s;
typedef int sunindextype;
// typedef int _Atomic;
typedef int vcomplexe;
typedef int ECO_ELEMENT;
typedef int LINK_NODE;
typedef int Scores;
typedef int cublasHandle_t;
typedef int hipblasHandle_t;
typedef int pixmap_t;
typedef int eigenPair;
typedef int oned_csc_graph;
typedef int oned_csr_graph;
typedef int tuple_graph;
typedef int _timer_t;
typedef int BCtype_d;
typedef int BCtype_s;
typedef int hclib_loop_domain_t;
typedef int double_sparse_matrix;
typedef int accessor_read_int;
typedef int POINT_T;
typedef int InputData;
typedef int basic_block;
typedef int Buffer;

typedef int subgrid_info;
typedef int info_type;
typedef int LinkedList;
typedef int Continuous;
typedef int par_str;
typedef int dim_str;
typedef int results_t;
typedef int gsl_odeiv2_system;
typedef int gsl_odeiv2_driver;
typedef int cufftDoubleComplex;
typedef int VlKDTreeNode;
typedef int Sphere;
typedef int Metal;
typedef int vl_bool;
typedef int gaf_ptr;
typedef int GAbool;
typedef int MMAL_STATUS_T;
typedef int COO_ENTRY_FLOAT;
typedef int BITMAPINFOHEADER;
typedef int Queue;
typedef int buckets;
typedef int Fifo;
typedef int Qureg;
typedef int threadqueue;
typedef int ELL;
typedef int nc_type;
typedef int random_t;
typedef int box_str;
typedef int UINT64;
typedef int FOUR_VECTOR;
typedef int ChainPtr;
typedef int copy_body_data;
typedef int const_tree;
typedef int const_tree;
typedef int cp_token;
typedef int Array;
typedef int Func;
typedef int mic_t;
typedef int model_t;
// typedef int __imag__;
typedef int tree_fn_t;
typedef int tributary__LME__;
typedef int IS;
typedef int Halo_points;
typedef int nbody_t;
typedef int piece_t;
typedef int TrieNode;
typedef int gsl_eigen_hermv_workspace;
typedef int CONV1D_DEC;
typedef int N_Vector_ID;
typedef int SCPformat;
typedef int SuperMatrix;
typedef int dimension_t;
typedef int MPI_Group;
typedef int q7_t;
typedef int Score;
typedef int Layer;
typedef int adaptavive_quadrature_intervals;
typedef int performance_measures;
typedef int symbols_t;
typedef int RSComplex;
typedef int ProgramData;
typedef int work_to_send;
typedef int Pole;
typedef int grid_t;
typedef int MATRIX;
typedef int XSizeHints;
typedef int workspace_t;
typedef int Weights;
typedef int Data;
typedef int Ugrid;
typedef int packed_edge;
typedef int STATE_CONSTR;
typedef int Color;
typedef int GUI;
typedef int BITMAPFILEHEADER;
typedef int GLsizei;
// typedef int omp_data_map_halo_region_info_t;
typedef int GridVector;
typedef int GridGeom;
// typedef int omp_device_type_info_t;
typedef int Measures;
typedef int Network;
typedef int error_t;
typedef int Pvoid_t;
typedef int PWord_t;
typedef int Word_t;
typedef int coordinate_t;
typedef int VectorND;
typedef int Mesh;
typedef int body_t;
typedef int PPM;
typedef int cl_uint;
typedef int Mosaic;
typedef int LU_t;
typedef int block64;
typedef int float32_t;
typedef int Object;
typedef int hero_dma_job_t;
typedef int csf_mode_type;
typedef int rank_info;
typedef int InputStruct;
typedef int Material;
typedef int meta_type_id;
typedef int splatt_mttkrp_ws;
typedef int csf_sparsity;
typedef int spmatrix_t;
typedef int func_ret_t;
typedef int Item;
typedef int List;
typedef int hrtime_t;
// typedef int mthread_t;
typedef int XImage;
typedef int Mandelbrot_Settings;
typedef int Frame_Settings;
typedef int apr_finfo_t;
typedef int apr_off_t;
typedef int LweParams;
typedef int triangle_t;
typedef int edge_t;
typedef int gk_i32kv_t;
typedef int vault_t;
typedef int ktedge_t;
// typedef int thread_ws;
typedef int N_Vector;
typedef int jdouble;
typedef int algoparam_t;
typedef int VECTOR;
typedef int PIXEL;
typedef int atimer_t;
typedef int lattice;
typedef int NN_data_set;
typedef int PDFPtr;
typedef int WSADATA;
typedef int MNCBLAS_LAYOUT;
typedef int MNCBLAS_TRANSPOSE;
typedef int float4;
typedef int timestamp_type;
typedef int coordinate;
typedef int hashtable_t;
typedef int calc_t;
typedef int result_t;
typedef int queuelist;
typedef int void_func_t;
typedef int _MMR;
typedef int sff_common_header;
// typedef int timespec;
typedef int Evaluation;
typedef int Setting;
typedef int param_t;
typedef int gsl_vector_view;
typedef int gsl_integration_workspace;
typedef int gsl_function;
typedef int glob_t;
typedef int herr_t;
typedef int parray;
typedef int t_sdVect;
typedef int t_bdVect;
typedef int t_sdMatr;
typedef int QSolved;
// typedef int omp_memspace_handle_t;
// typedef int omp_alloctrait_t;
typedef int data_ptr_res_t;
typedef int ZL_cstring;
typedef int MPDFEstimatorPtr;
typedef int ZL_ushort;
typedef int ZL_ulong;
typedef int hwloc_topology_t;
typedef int Feature;
typedef int double2;
typedef int TwoBody;
typedef int move_t;
typedef int int_func_t;
typedef int ECO_SETTINGS;
typedef int SRH_GRID;
typedef int Hashtable;
typedef int t_bdMatrVect;
typedef int MKL_INT;
typedef int gk_fkv_t;
typedef int GifFileType;
typedef int communicator_type;
typedef int ForceExchangeData;
typedef int HaloExchange;
typedef int packed_edge;
typedef int Inputs;
typedef int GridPoint;
typedef int LjPotential;
typedef int _config;
typedef int config;
typedef int reduction_fold_int_t;
typedef int _color;
typedef int QEvaluated;
typedef int POMP2_Task_handle;
typedef int t_sdMatrVect;
typedef int UT_hash_handle;
typedef int vector_t;
typedef int su_trace_t;
typedef int LayerStruct;
typedef int gdImagePtr;
typedef int ptrHybridTaus;
typedef int meta_face;
typedef int kjVec3f;
typedef int MPI_Comm;
typedef int idx_t;
typedef int wgt_t;
typedef int splatt_graph;
typedef int bin_header;
typedef int splatt_mat_norm;
typedef int sp_timer_t;
typedef int splatt_blas_int;
typedef int vtx_t;
typedef int splatt_file_type;
// typedef int omp_dist_info_t;
typedef int _Offload_status;
typedef int LcsResult;
typedef int Bank;
// typedef int __label__;
typedef int floatType;
typedef int splatt_kruskal;
typedef int LARGE_INTEGER;
typedef int BSLinSysMethod;
typedef int HsStablePtr;
typedef int particles_t;
typedef int gaspi_size_t;
typedef int BlockSparseMatrix;
typedef int _DOUBLE_;
typedef int AXON;
typedef int cudaStream_t;
typedef int lb_halo_enum_t;
typedef int DOUBLE;
typedef int io_info_t;
typedef int _Cilk_shared;
// typedef int omp_data_map_halo_exchange_info_t;
typedef int dynamic_weighted_edge_array;
typedef int weighted_edge;
typedef int GLfloat;
typedef int MatFloat;
typedef int GridPrim;
typedef int NEURON;
typedef int Tally;
typedef int OutStruct;
typedef int tmpOutStruct;
typedef int HANDLE;
typedef int hgraph_t;
typedef int hgraph_vwt_type;
typedef int long_long;
typedef int ZLOOPALL;
// typedef int omp_device_type_t;
typedef int Random;
typedef int public_struct;
typedef int private_struct;
typedef int OMPfraction_t;
typedef int SEQDATA;
typedef int LBM_Grid;
typedef int PROBNODE;
typedef int GLubyte;
typedef int Source;
typedef int encode_fct;
typedef int BasePotential;
typedef int EamPotential;
typedef int PList;
typedef int PyCFunction;
typedef int sph_haval128_4_context;
typedef int private_subformat_data;
typedef int ARCH_WORD;
typedef int edict_t;
typedef int Boolean;
typedef int Float;
typedef int Interp_data;
typedef int MPI_Request;
typedef int pTimer;
typedef int projPJ;
typedef int projUV;
typedef int meteo;
typedef int tkstruct;
typedef int QUO_contex;

typedef int kernel_t;
typedef int Record_Event;
typedef int sph_ripemd128_context;
typedef int sph_skein512_context;
typedef int ed25519_secret_key;
typedef int sph_tiger_context;
typedef int sph_whirlpool0_context;
typedef int BF_word;
typedef int fmt_data;
typedef int vec3_t;
typedef int STREAM_TYPE;

typedef int sevenzip_salt_t;
typedef int DES_bs_vector;
typedef int ed25519_public_key;
typedef int MD5_std_combined;
typedef int yescrypt_binary_t;
typedef int qboolean;
typedef int hestParm;
typedef int DC_ProcData;
typedef int hestOpt;
typedef int ARCH_WORD;
typedef int client_t;
typedef int argon2_context;
typedef int secp256k1_context;
typedef int secp256k1_pubkey;
typedef int Keccak_HashInstance;
typedef int has160_ctx;
typedef int sph_haval256_3_context;
typedef int keystore_salt;
typedef int custom_salt;
typedef int custom_salt_LUKS;
typedef int sph_md2_context;
typedef int aes_fptr_cbc;
typedef int ms_office_binary_blob;
typedef int sph_panama_context;
typedef int RC4_KEY;
typedef int u8;
typedef int ZIP_SIGS;
typedef int sph_ripemd160_context;
typedef int login_t;
typedef int sph_skein256_context;
typedef int snefru_ctx;
typedef int cudaError_t;


typedef int movevars_t;
typedef int cvar_t;
typedef int BOOL;
typedef int BF_binary;
typedef int DES_bs_combined;
typedef int fftw_plan;
typedef int AES_KEY;
typedef int argon2_type;
typedef int int_t;
typedef int options_t;
typedef int fftw_complex;
typedef int fftwf_plan;
typedef int fftwf_complex;
typedef int ComplexNumber;
typedef int Complex;
typedef int MPI_Win;
typedef int image_t;
typedef int VERT_T;
typedef int DOUBLE_T;
typedef int WEIGHT_T;
typedef int SimulationData;
typedef int rand_gen;
typedef int Weight;
typedef int MPI_Aint;
typedef int data_worker_to_master;
typedef int arm_status;
// typedef int float_t;
typedef int gmp_randstate_t;
typedef int MM_typecode;
typedef int Model;
// typedef int omp_sched_t;
typedef int isl_id_to_ast_expr;
typedef int yescrypt_params_t;
typedef int HMAC_SHA256_CTX;
typedef int buffer_128;
typedef int gost_ctx;
typedef int dyna_salt;
typedef int sph_whirlpool_context;
typedef int UTF32;
typedef int pset;
typedef int pcover;
typedef int random_draw_t;
typedef int s64Int;

typedef int meta_timer;
typedef int GraphMatrix;
typedef int LinkCell;
typedef int box_type;
typedef int gsl_histogram2d;
typedef int byte_array_t;
typedef int array_t;
typedef int hypre_Vector;
typedef int tImagen;
typedef int cvec1d;
typedef int params_t;
typedef int triangle_t;
typedef int FileNode;
typedef int gsl_vector;
typedef int xmap_t;
typedef int ListNode;
typedef int array_list_t;
typedef int Particle;
typedef int partition_t;
typedef int RASPISTILLYUV_STATE;
typedef int BCRS;
typedef int CRS;
typedef int Region;
typedef int Gamestate;
typedef int pixmap_;
typedef int pixm;
typedef int shmemx_ctx_t;
typedef int frontier;
typedef int organism;
typedef int Chrono;
typedef int complexe_double_t;
typedef int Sequence;


typedef int Table;
typedef int community_developer;
typedef int sorted_linked_list;
typedef int gsl_matrix_complex;
// typedef int omp_data_map_info_t;
typedef int STIMULI;
typedef int uword;
typedef int risky_asset;
typedef int Twofish_key;
typedef int City;

typedef int binary_blob;
typedef int PKZ_SALT;
typedef int VMS_word;
typedef int wpapsk_hash;
typedef int wpapsk_salt;
typedef int hccap_t;
typedef int Camera;
typedef int Atoms;
// typedef int omp_offloading_info_t;

typedef int ddef_t, dstatement_t;
typedef int bitlocker_custom_salt;
typedef int MD5_OUT;
typedef int MD5_IN;
typedef int BIG_HASH_OUT;
typedef int dfunction_t;
// typedef int __float128;
typedef int Nrrd;
typedef int quakeparms_t;
typedef int airMopper;
typedef int eval_t;
typedef int InterpolationObject;
typedef int gsl_permutation;
typedef int Zone;
typedef int thd_info;
typedef int val_t;
typedef int trace_t;
typedef int adj_t;
typedef int OGRSpatialReferenceH;
typedef int Vector3d;
typedef int real_t;
typedef int Mask;
typedef int yescrypt_local_t;
typedef int cell_t;
typedef int bn_layer;
typedef int conv_layer_t;
typedef int SHA_CTX;
typedef int tmg_graph;
typedef int community_t;
typedef int gather;
typedef int mymatriz;
typedef int Parameters;
typedef int winzip_salt;
typedef int ms_office_custom_salt;
typedef int bitarray;
typedef int CompressedMatrix;
typedef int RGBTRIPLE;
typedef int RGB;
typedef int RandomStruct_t;
typedef int PARAMS;
typedef int PARAM;
typedef int vl_type;
typedef int vl_size;
typedef int KEY_TYPE;
typedef int vertex_t;
typedef int sparseMatrix;
typedef int rcmQueue;
typedef int vertexNeibs;
typedef int cvector_vector_type;
typedef int vl_uindex;
typedef int animated_gif;
typedef int graphSDG;
typedef int byte_t;
typedef int ftensor_t;
typedef int rcomplex;
typedef int mutex_pool;
typedef int VR;
typedef int Graph;
typedef int strMdata;
typedef int CORPO;
typedef int Box;
typedef int vc_vector;
typedef int png_data;
typedef int DATA;
typedef int environment;
typedef int GRID;
typedef int Grid;
typedef int ComplexPlane;

typedef int md5bench_t;
typedef int Pair;
typedef int Edge;
typedef int mt19937state;
typedef int Mutant;
// typedef int Point;
typedef int uchar;
typedef int matriz_bloco_t;
typedef int neural_net;
typedef int neighbor_computation_package;
typedef int avi_t;
typedef int edit;
typedef int graph_t;
typedef int HMACMD5Context;
typedef int MVP;
typedef int Seqs_Details;
typedef int tree_t;
// typedef int ulong;
typedef int complexe_float_t;
typedef int hypre_Vector;
typedef int gsl_matrix;
typedef int blockCopy_type;
typedef int CCS;
typedef int FLOAT;
typedef int black;
typedef int AUDIT_INTERNAL_TIMES;
typedef int temporary_community_edge;
typedef int life_t;
typedef int BPNN;
typedef int openmpEvent;
typedef int json_t;
typedef int Gstat_t;
typedef int rankvec;
typedef int Params;
typedef int HPCC_Params;
typedef int real3;
typedef int mnt;
typedef int complex;
typedef int affinity_mask_t;
typedef int k_t;
typedef int dict_t;
typedef int complex_t;
typedef int UTF8;
// typedef int omp_data_map_t;
typedef int Stack;
typedef int Img;
typedef int Node;
typedef int Geometry;
typedef int CommMap;
typedef int gaspi_pointer_t;
typedef int sim_param_t;
typedef int Vector;
typedef int nbody_conf_t;
typedef int SparseMatrix;
typedef int dynamic_weighted_graph;
typedef int phase_execution_briefing;
typedef int LONG_T;
// typedef int omp_dev_stream_t;
typedef int timespec_t;
typedef int sinoscope_t;
typedef int sptensor_t;
typedef int qsort_args;
typedef int layer;
typedef int cJSON;
typedef int SpMatrix;
typedef int SHA256_CTX;
typedef int kernel_ann;
typedef int GraphNode;
typedef int LweSample;
typedef int forces_t;
typedef int LcsMatrix;
typedef int custom_salt;
typedef int encfs_common_custom_salt;
typedef int pretty_printer;
typedef int community_exchange;
typedef int node;
typedef int pool_layer;
typedef int mrg_state;
typedef int bitmap;
typedef int PPMImage;
typedef int PPMPixel;
typedef int PPMFilter;
typedef int LeNet5;
typedef int UTF16;
typedef int cell_type;
typedef int pixel_;
typedef int ret_data;
typedef int rgrid;
typedef int cplx_t;
typedef int spmat;
typedef int fvde_custom_salt;
typedef int NN_parameters;
typedef int solution_t;
typedef int problem_t;
typedef int real;
typedef int vptree;
typedef int Bucket;
typedef int Seq2Result;
typedef int Track;
typedef int node_t;
typedef int BSMLinSys;
typedef int wf;
typedef int quantum_matrix;
typedef int pgm_t;
typedef int Matriz_t;
typedef int pixel;
typedef int RGBColor;
typedef int Ltb_model;
typedef int basetype;
typedef int state_t;
typedef int wpapsk_password;
typedef int support_bucket_t;
typedef int eLargeOut_t;
typedef int lb_t;
typedef int dprograms_t;
typedef int limits_t;
typedef int Input;
typedef int hypre_CSRMatrix;
typedef int SimFlat;
typedef int uaf_qword;
typedef int particle_t;
typedef int list_res_t;
typedef int ELEMENT_TYPE;
typedef int TYPE;
typedef int COO;
typedef int pixe;
typedef int shmemx_domain_t;
typedef int uint8;
typedef int byte, Byte;
typedef int cgrid;
typedef int GRID_STRUCT;
typedef int adaptavive_quadrature_args;
typedef int globalvars_t;
// typedef int omp_event_t;
typedef int BF_salt;
typedef int MD5_data;
typedef int netadr_t;
typedef int supersite;
typedef int FFT_GRID;
typedef int swarm_t;
typedef int VlKMeans;
typedef int pixel_t;
typedef int fact_t;
typedef int trans_t;
typedef int yes_no_t;
typedef int NCPformat;
typedef int superlumt_options_t;
typedef int lapack_int;
typedef int Scene;
typedef int Light;
typedef int CPXLPptr;
typedef int Args_type;
typedef int block32;
typedef int OAES_OPTION;
typedef int ymm8r4_t;
typedef int Frame_Data;
typedef int Settings;
typedef int apr_status_t;
typedef int permutation_t;
typedef int apr_file_t;
typedef int task_list;
typedef int dom_state;
typedef int anbool;
typedef int path_t;
typedef int zmm16r4_t;
typedef int TFheGateBootstrappingCloudKeySet;
typedef int xy_t;
typedef int execution_settings;
typedef int u64Int;
typedef int complex_double;
typedef int UBspline_1d_s;
typedef int pcg32_random_t;
typedef int TableSize;
typedef int weight_t;
typedef int sph_whirlpool1_context;
typedef int AttenuateVars;
typedef int knode;
typedef int yescrypt_shared_t;
typedef int u32;
typedef int gaspi_pointer_t;
typedef int QUO_context;
typedef int leafabsemiss;
typedef int soilabsemiss;
typedef int u64;
typedef int keepass_salt_t;
typedef int SHA512_CTX;
typedef int MD5_word;
typedef int NuclideGridPoint;
typedef int ClusterDataPoint;
typedef int Renderer;
typedef int pbar;
// typedef int omp_grid_topology_t;
typedef int FIBITMAP;
typedef int vec2d_b;
typedef int Part;
typedef int INT_TYPE;
// typedef int INFO;
typedef int TIME_BLOCK_EXEC;
typedef int CRC32_t;
typedef int Canvas;
typedef int PGMImage;
typedef int psk_entry;
typedef int Move;
typedef int MYTYPE;
typedef int dft_seq;
typedef int sotl_device_t;
typedef int matrix_struct;
typedef int Filter;



// typedef int fd_set;
typedef int data_t;
typedef int splatt_csf;
// typedef float _Float64;
// typedef float __time_t;
typedef int XGCValues;
typedef int INT;
typedef int DATA_TYPE;
typedef int fmpz_comb_t;
typedef int mpfr_t;
typedef int cl_kernel, cl_command_queue, cl_mem, cl_context, cl_program, sotl_domain_t, sotl_atom_set_t, cl_event, cl_int, cl_mem;
typedef int __int64;
typedef int fptype;
typedef double COMPLEX_FLOAT;
typedef int Pixel3;
typedef int kdtree_t, hostrpc_varfn_double_t , hostrpc_varfn_uint_t;
typedef float gaspi_notification_id_t, gaspi_notification_t, gaspi_number_t, gaspi_queue_id_t;
typedef int MPI_Count;
typedef double REAL;
typedef int MD5_CTX;
typedef int WINDOW;
typedef int png_bytepp, __mmask8, hostrpc_varfn_uint_t, hostrpc_varfn_udouble_t;
typedef int mpfr_rnd_t;
typedef int cl_platform_id;
typedef int gsl_rng;
typedef int radweights;
typedef int Finalize;
typedef int Choud;
typedef int mpfr_prec_t;
// typedef int omp_lock_t;
typedef int Matrix_t;
typedef int structs;
// typedef int omp_cond_t;
typedef int MaxHeapNode;
typedef int SenseReversalOpenMP_Barrier;
typedef int dispatch_queue_t;
typedef int gsl_complex;
typedef int modularity_computing_package;
typedef int mpi_env_t;
typedef int EVP_CIPHER_CTX;
typedef int Display;
typedef int GC;
typedef int Window;
typedef int XColor;
typedef int hsize_t;
typedef int hid_t;
typedef int UCHAR, UINT;
typedef int mutant;
typedef int t_bdMatr, t_bfMatr;
typedef int t_bfMatrVect;
typedef int parallaldo;
typedef int t_bfVect;
typedef int t_sfVect;
typedef int t_sfMatr;
typedef int t_sfMatrVect;
typedef int dcomplexe;
typedef int POSITION;
typedef int tinydir_dir;
typedef int tinydir_file;
typedef int nmod_poly_t;
typedef int numa_node_t;
typedef int stopwatch;
typedef int Ray;
typedef int Hit;
typedef int Hitable_List;
typedef int BMPImage;
typedef int Clist;
typedef int data3D;
typedef int meta_callback, meta_event, meta_bool, meta_err;
typedef float dcomplex;
typedef float Pixmap;
typedef float XPoint;
typedef int JSAMPARRAY;
// typedef int INIT;
typedef int PyMODINIT_FUNC;
typedef int CommGrid;
typedef int VSLStreamStatePtr;
typedef int gk_graph_t;
typedef int gaspi_rank_t;
typedef int TBosque;
typedef int splatt_tile_type;
typedef int CadPt2ID;
typedef int PointArrayList_t;
typedef int MPIX_Request, MPI_Datatype, MPI_Count, MPI_Info;
typedef int splatt_idx_t, splatt_val_t;
typedef int _Cilk_spawn, mpf_t, atomic_uint, DeFrame;
typedef int __m64, mpz_t, SDL_GLContext, GLenum, SDL_Renderer, SDL_Texture, Gamemode;
typedef float Point, MAT, VEC;
typedef int cl_ulong;
typedef int sotl_platform_t;
typedef float float32x4_t, __mmask16;
typedef int SDL_Event, SDL_Window, SDL_DisplayMode;
typedef int MPI_Status, IplImage, body;
typedef int cl_device_id, cl_device_type, XSetWindowAttributes;
//
typedef int numa_flag_t, npy_intp;
typedef int logical, GLuint, PointArrayList_t;
typedef float SEXP;
// typedef int DIR, cpu_set_t;
typedef int boolean;
typedef int GLint;
typedef int GDALDatasetH;
typedef int GDALDriverH;
typedef int GDALRasterBandH;
// typedef int size_t;
typedef double REAL_T, REAL_t, INT_T;
// typedef int omp_device_t;
// typedef int omp_event_record_method_t;
typedef int PhotonStruct;
typedef int chain_t, args_t;
typedef int level_type;
// typedef int complex;
typedef int SquareMatrix;
typedef int gsl_rng_type;
typedef int gk_csr_t;
typedef int Matrix;
typedef int ModuleExport, ExceptionInfo, Image, MagickBooleanType, PixelPacket;
typedef int ImageType, ChannelType, RectangleInfo, ImageInfo, MagickSizeType, StreamHandler, BlobInfo,MapMode, MagickOffsetType;
typedef int IndexPacket, PixelPacket, MagickPixelPacket, VirtualPixelMethod, ClassType, ColorspaceType;
typedef int MagickPixelPacket, MagickRealType, Quantum, MagickPixelPacket, RegistryType;
typedef int QuantizeInfo, DrawInfo, PaintMethod, ExceptionType,InterpolatePixelMethod, MagickStatusType, QuantumType, AffineMatrix;
typedef int SemaphoreInfo, SegmentInfo, GravityType, StyleType, StretchType, KernelInfo, CompressionType, RenderingIntent;
typedef int FilterTypes, EndianType, DisposeType, TimerInfo, MagickProgressMonitor, Ascii85Info, Ascii85Info, ProfileInfo;
typedef int StringInfo, MagickThreadType, QuantumAny, LinkedListInfo, RandomInfo, NoiseType, SplayTreeInfo, ErrorInfo;
typedef int TypeMetric, DoublePixelPacket, LongPixelPacket, AlphaChannelType, ResolutionType, InterlaceType, OrientationType;
typedef int CacheView;
// typedef int omp_offloading_t;
typedef int HashFunction;
// typedef int __builtin_va_list;
typedef int CompositeOperator, PreviewType;
// typedef int __gnuc_va_list;
typedef int individual, Individual;
// typedef int va_list;
// typedef int __int8_t;
typedef int uint32x2_t;
typedef int uint32x4_t;
typedef int uint192_t;
// typedef int __uint8_t;
// typedef int omp_nest_lock_t;
typedef int BITMAP;
typedef int matrix_t;
typedef int region_t;
typedef int SDL_Surface;
typedef int matrixMultiOMP;
typedef int graymap_t;
typedef int color_t;
typedef int multiReturn;
typedef int MD4_CTX;
typedef int DIALOG;
// typedef int u_int64_t;
// typedef int u_int16_t;
// typedef int __int16_t;
// typedef int __uint16_t;
// typedef int u_int8_t;
// typedef int __int_least16_t;
// typedef int __uint_least16_t;
// typedef int __int32_t;
// typedef int __uint32_t;
// typedef int uint32;
// typedef int __int64_t;
// typedef int __uint64_t;
// typedef int __int_least32_t;
// typedef int __uint_least32_t;
typedef int __s8;
typedef int __u8;
typedef int __s16;
typedef int u16;
typedef int __u16;
typedef int __s32;
typedef int __u32;
typedef int __s64;
typedef int __u64;
typedef int _LOCK_T;
typedef int _LOCK_RECURSIVE_T;
typedef int _off_t;
// typedef int __dev_t;
// typedef int __uid_t;
// typedef int __gid_t;
typedef int _off64_t;
// typedef int _fpos_t;
// typedef int _ssize_t;
// typedef int wint_t;
typedef int _mbstate_t;
typedef int _flock_t;
typedef int _iconv_t;
typedef int __ULong;
// typedef int __FILE;
// typedef int ptrdiff_t;
// typedef int wchar_t;
// typedef int char16_t;
// typedef int char32_t;
// typedef int __off_t;
typedef int __pid_t;
// typedef int __loff_t;
// typedef int u_char;
// typedef int u_short;
// typedef int u_int;
// typedef int u_long;
// typedef int ushort;
// typedef int uint;
// typedef int clock_t;
// typedef int time_t;
typedef int daddr_t;
// typedef int caddr_t;
// typedef int ino_t;
// typedef int off_t;
// typedef int dev_t;
// typedef int uid_t;
// typedef int gid_t;
typedef int pid_t;
typedef int key_t;
// typedef int ssize_t;
// typedef int mode_t;
// typedef int nlink_t;
// typedef int fd_mask;
// typedef int _types_fd_set;
// typedef int clockid_t;
// typedef int timer_t;
// typedef int useconds_t;
// typedef int suseconds_t;
// typedef int gaspi_offset_t;
// typedef int FILE;
// typedef int fpos_t;
// typedef int cookie_read_function_t;
// typedef int cookie_write_function_t;
// typedef int cookie_seek_function_t;
// typedef int cookie_close_function_t;
// typedef int cookie_io_functions_t;
// typedef int div_t;
// typedef int ldiv_t;
// typedef int lldiv_t;
// typedef int sigset_t;
// typedef int __sigset_t;
// typedef int _sig_func_ptr;
// typedef int sig_atomic_t;
typedef int __tzrule_type;
typedef int __tzinfo_type;
// typedef int mbstate_t;
typedef int sem_t;
// typedef int pthread_t;
// typedef int pthread_attr_t;
// typedef int pthread_mutex_t;
// typedef int pthread_mutexattr_t;
// typedef int pthread_cond_t;
// typedef int pthread_condattr_t;
// typedef int pthread_key_t;
// typedef int pthread_once_t;
// typedef int pthread_rwlock_t;
// typedef int pthread_rwlockattr_t;
// typedef int pthread_spinlock_t;
// typedef int pthread_barrier_t;
// typedef int pthread_barrierattr_t;
typedef int jmp_buf;
typedef int rlim_t;
typedef int sa_family_t;
typedef int sigjmp_buf;
typedef int stack_t;
typedef int siginfo_t;
typedef int z_stream;

/* C99 exact-width integer types */
// typedef int int8_t;
// typedef int uint8_t;
// typedef int int16_t;
// typedef int uint16_t;
// typedef int int32_t;
// typedef int uint32_t;
// typedef int int64_t;
// typedef int uint64_t;

/* C99 minimum-width integer types */
// typedef int int_least8_t;
// typedef int uint_least8_t;
// typedef int int_least16_t;
// typedef int uint_least16_t;
// typedef int int_least32_t;
// typedef int uint_least32_t;
// typedef int int_least64_t;
// typedef int uint_least64_t;

/* C99 fastest minimum-width integer types */
// typedef int int_fast8_t;
// typedef int uint_fast8_t;
// typedef int int_fast16_t;
// typedef int uint_fast16_t;
// typedef int int_fast32_t;
// typedef int uint_fast32_t;
// typedef int int_fast64_t;
// typedef int uint_fast64_t;

/* C99 integer types capable of holding object pointers */
// typedef int intptr_t;
// typedef int uintptr_t;

/* C99 greatest-width integer types */
// typedef int intmax_t;
// typedef int uintmax_t;

/* C99 stdbool.h bool type. _Bool is built-in in C99 */
// typedef _Bool bool;

/* Mir typedefs */
typedef void* MirEGLNativeWindowType;
typedef void* MirEGLNativeDisplayType;
typedef struct MirConnection MirConnection;
typedef struct MirSurface MirSurface;
typedef struct MirSurfaceSpec MirSurfaceSpec;
typedef struct MirScreencast MirScreencast;
typedef struct MirPromptSession MirPromptSession;
typedef struct MirBufferStream MirBufferStream;
typedef struct MirPersistentId MirPersistentId;
typedef struct MirBlob MirBlob;
typedef struct MirDisplayConfig MirDisplayConfig;

typedef int realtype;
typedef int mxArray;
typedef int Uint8;
typedef int Uint16;
typedef int Uint32;
#define USE_OPENMP 1
/*python*/
typedef int PyObject;
#define Py_RETURN_NONE 0
#define PyArray_LONG 1
typedef int PyArrayObject;
typedef struct PyMethodDef_t {
    const char  *ml_name;   /* The name of the built-in function/method */
//    PyCFunction ml_meth;    /* The C function that implements it */
  //  int         ml_flags;   /* Combination of METH_xxx flags, which mostly
    const char  *ml_doc;    /* The __doc__ attribute, or NULL */
};

typedef struct PyMethodDef_t PyMethodDef;

/* xcb typedefs */
typedef struct xcb_connection_t xcb_connection_t;
// typedef uint32_t xcb_window_t;
// typedef uint32_t xcb_visualid_t;

/* C11 stdatomic.h types */
/*typedef _Atomic(_Bool)              atomic_bool;
typedef _Atomic(char)               atomic_char;
typedef _Atomic(signed char)        atomic_schar;
typedef _Atomic(unsigned char)      atomic_uchar;
typedef _Atomic(short)              atomic_short;
typedef _Atomic(unsigned short)     atomic_ushort;
typedef _Atomic(int)                atomic_int;
typedef _Atomic(unsigned int)       atomic_uint;
typedef _Atomic(long)               atomic_long;
typedef _Atomic(unsigned long)      atomic_ulong;
typedef _Atomic(long long)          atomic_llong;
typedef _Atomic(unsigned long long) atomic_ullong;
typedef _Atomic(uint_least16_t)     atomic_char16_t;
typedef _Atomic(uint_least32_t)     atomic_char32_t;
typedef _Atomic(wchar_t)            atomic_wchar_t;
typedef _Atomic(int_least8_t)       atomic_int_least8_t;
typedef _Atomic(uint_least8_t)      atomic_uint_least8_t;
typedef _Atomic(int_least16_t)      atomic_int_least16_t;
typedef _Atomic(uint_least16_t)     atomic_uint_least16_t;
typedef _Atomic(int_least32_t)      atomic_int_least32_t;
typedef _Atomic(uint_least32_t)     atomic_uint_least32_t;
typedef _Atomic(int_least64_t)      atomic_int_least64_t;
typedef _Atomic(uint_least64_t)     atomic_uint_least64_t;
typedef _Atomic(int_fast8_t)        atomic_int_fast8_t;
typedef _Atomic(uint_fast8_t)       atomic_uint_fast8_t;
typedef _Atomic(int_fast16_t)       atomic_int_fast16_t;
typedef _Atomic(uint_fast16_t)      atomic_uint_fast16_t;
typedef _Atomic(int_fast32_t)       atomic_int_fast32_t;
typedef _Atomic(uint_fast32_t)      atomic_uint_fast32_t;
typedef _Atomic(int_fast64_t)       atomic_int_fast64_t;
typedef _Atomic(uint_fast64_t)      atomic_uint_fast64_t;
typedef _Atomic(intptr_t)           atomic_intptr_t;
typedef _Atomic(uintptr_t)          atomic_uintptr_t;
typedef _Atomic(size_t)             atomic_size_t;
typedef _Atomic(ptrdiff_t)          atomic_ptrdiff_t;
typedef _Atomic(intmax_t)           atomic_intmax_t;
typedef _Atomic(uintmax_t)          atomic_uintmax_t;
typedef struct atomic_flag { atomic_bool _Value; } atomic_flag;
typedef enum memory_order {
  memory_order_relaxed,
  memory_order_consume,
  memory_order_acquire,
  memory_order_release,
  memory_order_acq_rel,
  memory_order_seq_cst
} memory_order;
*/
#endif
