compound_statement__
	declaration__
		binary_expression
	__declaration
	declaration
	declaration
	declaration
	for_statement__
		assignment_expression
		binary_expression
		update_expression
		compound_statement__
			expression_statement__
				assignment_expression__
					subscript_expression
				__assignment_expression
			__expression_statement
		__compound_statement
	__for_statement
	for_statement__
		assignment_expression
		binary_expression
		assignment_expression
		compound_statement__
			expression_statement__
				assignment_expression
			__expression_statement
			expression_statement__
				assignment_expression
			__expression_statement
			for_statement__
				compound_statement__
					expression_statement__
						assignment_expression__
							binary_expression__
								subscript_expression
							__binary_expression
						__assignment_expression
					__expression_statement
					expression_statement__
						assignment_expression__
							binary_expression__
								binary_expression
							__binary_expression
						__assignment_expression
					__expression_statement
					expression_statement__
						assignment_expression__
							subscript_expression
							binary_expression
						__assignment_expression
					__expression_statement
					expression_statement__
						assignment_expression
					__expression_statement
					expression_statement__
						update_expression
					__expression_statement
					if_statement__
						parenthesized_expression__
							binary_expression
						__parenthesized_expression
						break_statement
					__if_statement
					expression_statement__
						assignment_expression
					__expression_statement
				__compound_statement
			__for_statement
			expression_statement__
				call_expression__
					binary_expression__
						binary_expression
					__binary_expression
				__call_expression
			__expression_statement
			expression_statement__
				assignment_expression__
					binary_expression
				__assignment_expression
			__expression_statement
		__compound_statement
	__for_statement
	return_statement
__compound_statement
